---

spring:
  profiles:
    active: test

  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:file:~\Documents\db
    username: sa
    password:
    driverClassName: org.h2.Driver
  flyway:
    baseline-on-migrate: false
    locations:
      - classpath:db/migration/h2